site_name: MIN - Image Analysis Courses

nav:
  - Welcome: index.md
  - Course Preparation: 
    - General Information: coursepreparation/generalprep.md
    - Image Database OMERO: coursepreparation/omero.md
    - The HIVE: coursepreparation/thehive.md
  - Course "Basic Image Analysis":
    - Welcome to the Course: basic/index.md
    
    - Basics of Image Analysis: 
        - Introduction to Bioimage Analysis: basic/basics/introductionbasics.md
        - Introduction to Fiji/ImageJ: basic/basics/fiji.md
        - "Tutorial 1: Inspect Images & Perform Your First Measurements": basic/basics/tutorial_1_fiji.md
        - "Tutorial 2: Creating Figures": basic/basics/tutorial_2_creatingfigures.md
        - "Task: Figure Challenge": basic/basics/figurechallenge.md
    - Image Processing and Analysis:
        - The Image Analysis Workflow: basic/analysis/workflow.md
        - "Tutorial 3: Analyse your Images": basic/analysis/tutorial_3_analysis.md
        - "Task:  Manual Image Analysis": basic/analysis/task_manualanalysis.md
    - Image Segmentation using AI:
        - Image Segmentation using ML: basic/mlforsegmentation/pixelclassification.md
        - "Tutorial 4: Pixel Classification - Weka": basic/mlforsegmentation/tutorial_4_weka.md
        - Image Segementation using DL: basic/mlforsegmentation/dl.md
        - "Tutorial 5: CellPose": basic/mlforsegmentation/tutorial_5_cellpose.md
        - "Task: Analysis Workflow using Fiji and Cellpose": basic/mlforsegmentation/task_cellposeanalysis.md
        
  - Quiz "Basic Image Analysis":
    -  Self assessment: basic/quiz/basics_selfassessment.md 


theme:
   name: readthedocs
   logo: assets/logo.png
   favicon: assets/favicon.png

plugins:
  - quiz-plugin

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  
