site_name: MIN - Image Analysis Courses
nav:
  - Welcome: index.md
  - Basic Image Analysis: 
    - Basics of Image Analysis: 
        - Introduction to Bioimage Analysis: basic/basics/introductionbasics.md
        - Introduction to Fiji/ImageJ: basic/basics/fiji.md
        - "Fiji Tutorial 1: Open and inspect Images": basic/basics/fiji_tutorial_1.md
        - "Fiji Tutorial 2: Basic Image Processing": basic/basics/fiji_tutorial_2.md
        - Updating Fiji: basic/basics/update.md
        - Creating Figures: basic/basics/creatingfigures.md
        - Figure Challenge: basic/basics/figurechallenge.md
    - AI for Segmentation: 
        - Image Segmentation Bascis: basic/mlforsegmentation/imagesegmentation.md
        - Pixel classification: basic/mlforsegmentation/pixelclassification.md
        - Deep Learning: basic/mlforsegmentation/dl.md
    - Reproducible Image Analysis Workflows:
        - Reproducible Image Analysis: basic/reproducibleanalysis/introrepanalysis.md
        - CellProfiler for Batch Analysis: basic/reproducibleanalysis/cellprofiler.md
        - CellProfiler Tutorial: basic/reproducibleanalysis/cellprofilertutorial.md
 
  - Advanced Image Analysis: 
    - Advanced Image Analysis: advanced/advanced.md
theme:
   name: readthedocs
   logo: assets/logo.png
   favicon: assets/favicon.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
