site_name: MIN - Image Analysis Courses
nav:
  - Welcome: index.md
  - Course Preparation: 
    - General Information: coursepreparation/generalprep.md
    - Image Database OMERO: coursepreparation/omero.md
    - JupyterHub: coursepreparation/jupyterhub.md
    - The HIVE: coursepreparation/thehive.md
  - Course "Basic Image Analysis":
    - Basics of Image Analysis: 
        - Welcome to the Course: basic/index.md
        - Introduction to Bioimage Analysis: basic/basics/introductionbasics.md
        - Introduction to Fiji/ImageJ: basic/basics/fiji.md
        - Creating Figures: basic/basics/creatingfigures.md
        - Figure Challenge: basic/basics/figurechallenge.md
    - AI for Segmentation: 
        - Image Segmentation Bascis: basic/mlforsegmentation/imagesegmentation.md
        - Pixel classification: basic/mlforsegmentation/pixelclassification.md
        - Deep Learning: basic/mlforsegmentation/dl.md
    - Reproducible Image Analysis Workflows:
        - Reproducible Image Analysis: basic/reproducibleanalysis/introrepanalysis.md
        - CellProfiler for Batch Analysis: basic/reproducibleanalysis/cellprofiler.md
        - CellProfiler Tutorial: basic/reproducibleanalysis/cellprofilertutorial.md

theme:
   name: readthedocs
   logo: assets/logo.png
   favicon: assets/favicon.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
