site_name: MIN - Image Analysis Courses
nav:
  - Welcome: index.md
  - Course Preparation: 
    - General Information: coursepreparation/generalprep.md
    - Image Database OMERO: coursepreparation/omero.md
    - JupyterHub: coursepreparation/jupyterhub.md
    - The HIVE: coursepreparation/thehive.md
  - Course "Basic Image Analysis":
    - Welcome to the Course: basic/index.md
    
theme:
   name: readthedocs
   logo: assets/logo.png
   favicon: assets/favicon.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
