site_name: MIN - Image Analysis Courses

nav:
  - Welcome: index.md
  - Course Preparation: 
    - General Information: coursepreparation/generalprep.md
    - Image Database OMERO: coursepreparation/omero.md
    - The HIVE: coursepreparation/thehive.md
  - Course "Basic Image Analysis":
    - Welcome to the Course: basic/index.md
    
    - Basics of Image Analysis: 
        - Introduction to Bioimage Analysis: basic/basics/introductionbasics.md
        - Introduction to Fiji/ImageJ: basic/basics/fiji.md
        - "Tutorial: Inspect Images & Perform Your First Measurements": basic/basics/fiji_tutorial_1.md
        - "Tutorial: Creating Figures": basic/basics/creatingfigures.md
        - "Task: Figure Challenge": basic/basics/figurechallenge.md
    - Image Processing and Analysis:
        - The Image Analysis Workflow: basic/analysis/workflow.md
        - Image Segmentation Basics: basic/segmentation/imagesegmentation.md
        - "Tutorial: Thresholding your Images": basic/segmentation/thresholding.md
        - Image Preprocessing: basic/basics/preprocessing.md
        - "Tutorial: Basic Image Processing": basic/segmentation/tutorialpreprocessing.md
        - Refine Detections: basic/segmentation/detections.md
        - "Tutorial: Watershed": basic/segmentation/watershed.md
        - Analyse Your Data: basic/analysis/analyseparticles.md
        - "Tutorial: Analyse Particles": basic/analysis/tutorialanalyseparticles.md
        - "Task:  Manual Image Analysis": basic/analysis/taskmanualanalysis.md
    - Image Segmentation using AI:
        - Image Segmentation using ML: basic/mlforsegmentation/pixelclassification.md
        - Best Practices: basic/mlforsegmentation/ilastik.md
        - "Tutorial: Pixel Classification - Weka": basic/mlforsegmentation/ilastik_v2.md
        - Image Segementation using DL: basic/mlforsegmentation/dl.md
        - "Tutorial: CellPose": basic/mlforsegmentation/cellpose.md
        - "Task: Analysis Workflow using Fiji and Cellpose": basic/mlforsegmentation/fullworkflow.md
        
  - Quiz "Basic Image Analysis":
    -  Self assessment: basic/quiz/basics_selfassessment.md 


theme:
   name: readthedocs
   logo: assets/logo.png
   favicon: assets/favicon.png

plugins:
  - quiz-plugin

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  
