site_name: MIN - Image Analysis Courses

nav:
  - Welcome: index.md
  - Course Preparation: 
    - General Information: coursepreparation/generalprep.md
    - Image Database OMERO: coursepreparation/omero.md
    - The HIVE: coursepreparation/thehive.md
  - Course "Basic Image Analysis":
    - Welcome to the Course: basic/index.md
    - Basics of Image Analysis: 
        - Introduction to Bioimage Analysis: basic/basics/introductionbasics.md
        - Introduction to Fiji/ImageJ: basic/basics/fiji.md
        - "Tutorial 1: Inspect Images & Perform Your First Measurements": basic/basics/tutorial_1_fiji.md
        - "Tutorial 2: Creating Figures": basic/basics/tutorial_2_creatingfigures.md
        - "Task: Figure Challenge": basic/basics/figurechallenge.md
    - Image Processing and Analysis:
        - The Image Analysis Workflow: basic/analysis/workflow.md
        - "Tutorial 3: Analyse your Images": basic/analysis/tutorial_3_analysis.md
        - "Task:  Manual Image Analysis": basic/analysis/task_manualanalysis.md
    - Image Segmentation using AI:
        - Image Segmentation using ML: basic/mlforsegmentation/pixelclassification.md
        - "Tutorial 4: Pixel Classification - Weka": basic/mlforsegmentation/tutorial_4_weka.md
        - Image Segementation using DL: basic/mlforsegmentation/dl.md
        - "Tutorial 5: CellPose": basic/mlforsegmentation/tutorial_5_cellpose.md
        - "Task: Analysis Workflow using Fiji and Cellpose": basic/mlforsegmentation/task_cellposeanalysis.md

  - Course "Reproducible bioimage analysis of morphology and dynamics":
    - Welcome to the Course: advanced/index.md
    - Image Segmentation using AI:
        - Image Segmentation using ML: advanced/dl/pixelclassification.md
        - Ilastik: advanced/dl/ilastik.md
        - "Tutorial 1: Pixel Classification - ilastik": advanced/dl/ilastik_v2.md
        - Image Segementation using DL: advanced/dl/dl.md
        - Cellpose: advanced/dl/cellpose_background.md
        - "Tutorial 2: CellPose": advanced/dl/cellpose.md
        - "Checklist: Correct Segmentation": advanced/checklist_segmentation.md
    - Reproducible Image Analysis:
        - Introduction To Reproducible Image Analysis: advanced/repIA.md
        - CellProfiler: advanced/cellprofiler/cellprofiler.md
        - "Tutorial 3: CellProfiler - Part 1": advanced/cellprofiler/tutorial_3_p1_cellprofiler.md
        - "Intermezzo: Cheat-Sheet CellProfiler Modules": advanced/cellprofiler/cheatsheets_half.md
        - "Tutorial 3: CellProfiler - Part 2": advanced/cellprofiler/tutorial_3_p2_cellprofiler.md
        - "Task: Reproducible Image Analysis with CellProfiler": advanced/cellprofiler/task_cellprofiler.md
        - "Checklist: Reproducible Image Analysis": advanced/checklist_ria.md
    - Cell Tracking:
        - Cell Tracking: advanced/celltracking.md
        - "Tutorial 4: TrackMate": advanced/tutorial_4_trackmate.md
        - "Checklist: Correct Tracking": advanced/checklist_tracking.md

  - Quiz "Basic Image Analysis":
    -  Self assessment: basic/quiz/basics_selfassessment.md 




theme:
   name: readthedocs
   logo: assets/logo.png
   favicon: assets/favicon.png

plugins:
  - quiz-plugin

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  
